
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerse
    username: root
    password: Wall3t53v1ce

  jpa:
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

