server:
  port: 9005
  error:
    include-message: always

spring:
  application:
    name: springboot-course

  jwt:
    key: ${JWT_SECRET}

  profiles:
    active: dev

stripe:
  secretKey: ${API_SECRET_KEY}
  webhookKey: ${WEBHOOK_SECRET_KEY}
  baseUrl:

